/*
 * service_name.h
 *
 * Service names known to NRF
 */

#ifndef _OpenAPI_service_name_H_
#define _OpenAPI_service_name_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_service_name_NULL = 0, OpenAPI_service_name_nnrf_nfm, OpenAPI_service_name_nnrf_disc, OpenAPI_service_name_nnrf_oauth2, OpenAPI_service_name_nudm_sdm, OpenAPI_service_name_nudm_uecm, OpenAPI_service_name_nudm_ueau, OpenAPI_service_name_nudm_ee, OpenAPI_service_name_nudm_pp, OpenAPI_service_name_nudm_niddau, OpenAPI_service_name_nudm_mt, OpenAPI_service_name_nudm_ssau, OpenAPI_service_name_nudm_rsds, OpenAPI_service_name_namf_comm, OpenAPI_service_name_namf_evts, OpenAPI_service_name_namf_mt, OpenAPI_service_name_namf_loc, OpenAPI_service_name_namf_mbs_comm, OpenAPI_service_name_namf_mbs_bc, OpenAPI_service_name_nsmf_pdusession, OpenAPI_service_name_nsmf_event_exposure, OpenAPI_service_name_nsmf_nidd, OpenAPI_service_name_nausf_auth, OpenAPI_service_name_nausf_sorprotection, OpenAPI_service_name_nausf_upuprotection, OpenAPI_service_name_nnef_pfdmanagement, OpenAPI_service_name_nnef_smcontext, OpenAPI_service_name_nnef_eventexposure, OpenAPI_service_name_nnef_eas_deployment_info, OpenAPI_service_name__3gpp_cp_parameter_provisioning, OpenAPI_service_name__3gpp_device_triggering, OpenAPI_service_name__3gpp_bdt, OpenAPI_service_name__3gpp_traffic_influence, OpenAPI_service_name__3gpp_chargeable_party, OpenAPI_service_name__3gpp_as_session_with_qos, OpenAPI_service_name__3gpp_msisdn_less_mo_sms, OpenAPI_service_name__3gpp_service_parameter, OpenAPI_service_name__3gpp_monitoring_event, OpenAPI_service_name__3gpp_nidd_configuration_trigger, OpenAPI_service_name__3gpp_nidd, OpenAPI_service_name__3gpp_analyticsexposure, OpenAPI_service_name__3gpp_racs_parameter_provisioning, OpenAPI_service_name__3gpp_ecr_control, OpenAPI_service_name__3gpp_applying_bdt_policy, OpenAPI_service_name__3gpp_mo_lcs_notify, OpenAPI_service_name__3gpp_time_sync, OpenAPI_service_name__3gpp_am_influence, OpenAPI_service_name__3gpp_am_policyauthorization, OpenAPI_service_name__3gpp_akma, OpenAPI_service_name__3gpp_eas_deployment, OpenAPI_service_name__3gpp_iptvconfiguration, OpenAPI_service_name__3gpp_mbs_tmgi, OpenAPI_service_name__3gpp_mbs_session, OpenAPI_service_name__3gpp_authentication, OpenAPI_service_name__3gpp_asti, OpenAPI_service_name_npcf_am_policy_control, OpenAPI_service_name_npcf_smpolicycontrol, OpenAPI_service_name_npcf_policyauthorization, OpenAPI_service_name_npcf_bdtpolicycontrol, OpenAPI_service_name_npcf_eventexposure, OpenAPI_service_name_npcf_ue_policy_control, OpenAPI_service_name_npcf_am_policyauthorization, OpenAPI_service_name_nsmsf_sms, OpenAPI_service_name_nnssf_nsselection, OpenAPI_service_name_nnssf_nssaiavailability, OpenAPI_service_name_nudr_dr, OpenAPI_service_name_nudr_group_id_map, OpenAPI_service_name_nlmf_loc, OpenAPI_service_name_n5g_eir_eic, OpenAPI_service_name_nbsf_management, OpenAPI_service_name_nchf_spendinglimitcontrol, OpenAPI_service_name_nchf_convergedcharging, OpenAPI_service_name_nchf_offlineonlycharging, OpenAPI_service_name_nnwdaf_eventssubscription, OpenAPI_service_name_nnwdaf_analyticsinfo, OpenAPI_service_name_nnwdaf_datamanagement, OpenAPI_service_name_nnwdaf_mlmodelprovision, OpenAPI_service_name_ngmlc_loc, OpenAPI_service_name_nucmf_provisioning, OpenAPI_service_name_nucmf_uecapabilitymanagement, OpenAPI_service_name_nhss_sdm, OpenAPI_service_name_nhss_uecm, OpenAPI_service_name_nhss_ueau, OpenAPI_service_name_nhss_ee, OpenAPI_service_name_nhss_ims_sdm, OpenAPI_service_name_nhss_ims_uecm, OpenAPI_service_name_nhss_ims_ueau, OpenAPI_service_name_nhss_gba_sdm, OpenAPI_service_name_nhss_gba_ueau, OpenAPI_service_name_nsepp_telescopic, OpenAPI_service_name_nsoraf_sor, OpenAPI_service_name_nspaf_secured_packet, OpenAPI_service_name_nudsf_dr, OpenAPI_service_name_nudsf_timer, OpenAPI_service_name_nnssaaf_nssaa, OpenAPI_service_name_nnssaaf_aiw, OpenAPI_service_name_naanf_akma, OpenAPI_service_name_n5gddnmf_discovery, OpenAPI_service_name_nmfaf_3dadm, OpenAPI_service_name_nmfaf_3cadm, OpenAPI_service_name_neasdf_dnscontext, OpenAPI_service_name_neasdf_baselinednspattern, OpenAPI_service_name_ndccf_dm, OpenAPI_service_name_ndccf_cm, OpenAPI_service_name_nnsacf_nsac, OpenAPI_service_name_nnsacf_slice_ee, OpenAPI_service_name_nmbsmf_tmgi, OpenAPI_service_name_nmbsmf_mbssession, OpenAPI_service_name_nadrf_dm, OpenAPI_service_name_nbsp_gba, OpenAPI_service_name_ntsctsf_time_sync, OpenAPI_service_name_ntsctsf_qos_tscai, OpenAPI_service_name_ntsctsf_asti, OpenAPI_service_name_npkmf_keyreq, OpenAPI_service_name_nmnpf_npstatus, OpenAPI_service_name_niwmsc_smservice, OpenAPI_service_name_nmbsf_mbsuserserv, OpenAPI_service_name_nmbsf_mbsuserdataing, OpenAPI_service_name_nmbstf_distsession, OpenAPI_service_name_npanf_prosekey } OpenAPI_service_name_e;

char* OpenAPI_service_name_ToString(OpenAPI_service_name_e service_name);

OpenAPI_service_name_e OpenAPI_service_name_FromString(char* service_name);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_service_name_H_ */

